scrimio/dota_mm/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.Index, name="index"),
	# Team Generic View
	url(r'^teams/create/$', views.TeamCreate, name="team-create"),
	# Team Specific View
	url(r'^teams/(?P<pk>[0-9]+)/$', views.TeamView, name="team-view"),
	url(r'^teams/(?P<pk>[0-9]+)/edit', views.TeamEditView, name="team-edit"),
	# User Specific View
	url(r'^user/teams/$', views.PlayerTeamView, name="player-team-list"),
	# Match Specific View
	url(r'^match/(?P<pk>[0-9]+)/$', views.GameMatchView, name="match-view"),
	# Match Specific API
	url(r'^api/match/(?P<pk>[0-9]+)/$', views.API_MatchDetail.as_view(), name="match-view"),
	# User Specific API
	url(r'^api/user/(?P<pk>[0-9]+)/$', views.API_GamePlayerDetail.as_view(), name="api-player-detail"),
	url(r'^api/user/(?P<pk>[0-9]+)/teams/$', views.API_GamePlayerTeamList.as_view(), name="api-team-player-list"),
	# Team Generic API
	url(r'^api/teams/$', views.API_TeamCreate.as_view(), name="api-team-list"),
	# Team Specific API
	url(r'^api/team/(?P<pk>[0-9]+)/$', views.API_TeamDetail.as_view(), name="api-team-detail"),
	url(r'^api/team/(?P<pk>[0-9]+)/update/$', views.API_TeamEdit.as_view(), name="api-team-update"),
	url(r'^api/team/(?P<pk>[0-9]+)/destroy/$', views.API_TeamDelete.as_view(), name="api-team-destroy"),
]

scrimio/player_acct/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
	url(r'^dashboard/$', views.player_dashboard, name='user-dashboard'),
	url(r'^friends/$', views.player_friends_list, name='user-friends'),
	url(r'^new/$', views.player_new, name="player-new"),
	url(r'^api/user/$', views.UserList.as_view(), name="api-player-list"),
	url(r'^api/user/(?P<pk>[0-9]+)/$', views.UserDetail.as_view(), name="api-player-detail"),
]

scrimio/scrimio/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from . import views


urlpatterns = [
    url(r'', include('social.apps.django_app.urls', namespace='social')),     # Django Social Auth Login
    url(r'^$', views.index, name='index'),                                    # Index Page
    url(r'^user/', include('player_acct.urls', namespace='user')),            # Scrimio User Information
    url(r'^dota/', include('dota_mm.urls', namespace='dota')),                # Scrimio User Information
    url(r'^admin/', admin.site.urls),                                         # Admin Page
]

scrimio/player_acct/models.py
from django.db import models
from django.contrib.auth.models import User
import dota_mm

# Scrimio wide player
# 	- Tracks site wide profile data
class Player(models.Model):
	user = models.OneToOneField(User, primary_key=True, related_name="player", on_delete=models.CASCADE) # Proxies the django User
	username = models.SlugField(unique=True, max_length=15, default=("NotFound%s" % id))
	is_online = models.BooleanField(default=False) # Is user currently online?
	steam_id = models.CharField(max_length=29, default='null', blank=True) 	# Steam ID used to connect to Steam Games
	bnet_id = models.CharField(max_length=19, default='null', blank=True) 	# BNet User ID to connect to BNet Games
	friends = models.ManyToManyField("self", blank=True)										

	def __unicode__(self):
		return self.username

scrimio/player_acct/views.py
from django.contrib.auth.models import User
from .models import Player
from django.shortcuts import render
from rest_framework import generics
from .serializers import PlayerSerializer
from django.views.decorators.csrf import requires_csrf_token

from player_acct.models import Player

#--------------# User Pages #--------------#

# Player Dashboard
def player_dashboard(request):
	username = None
	if request.user.is_authenticated():
		try: 
			player = Player.objects.get(user=request.user) # Try to find this player
			user = request.user
			return render(request, 'player_acct/dashboard.html', {'user': user,'player_id': request.user.pk})
		except Player.DoesNotExist:
			return render(request, 'player_acct/user_new.html', {'user': request.user})

# Player Friends List Page 
def player_friends_list(request):
	if request.user.is_authenticated():
		try: 
			player = Player.objects.get(user=request.user) # Try to find this player
			user = request.user
			return render(request, 'player_acct/friends_list.html', {'user': user})
		except Player.DoesNotExist:
			return render(request, 'player_acct/user_new.html', {'user': request.user})

# Player Creation Page
@requires_csrf_token # Ensure CSRF token is given despite lack of {% csrf_token %} in template
def player_new(request):
	if request.user.is_authenticated():
		try:
			player = Player.objects.get(user=request.user) # Try to find this player
		except Player.DoesNotExist: # Redirect to new player form player not found
			player = None
			return render(request, 'player_acct/user_new.html', {'user': request.user})

		return render(request, 'player_acct/dashboard.html', {'user':request.user})

	return render(request, 'scrimio/index.html')

#---------------# User API #---------------#

# Player CREATE
class UserList(generics.ListCreateAPIView):
	queryset = Player.objects.all()
	serializer_class = PlayerSerializer

# Player GET, PATCH, DESTROY
class UserDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Player.objects.all()
    serializer_class = PlayerSerializer

scrimio/player_acct/templates/player_acct/dashboard.html
{% extends "scrimio/base.html" %}
{% load static %}

{% block local_javascript %}
	{{ block.super }}
	<script type="text/javascript" src="{% static 'player_acct/js/expandable.js' %}"></script>
{% endblock local_javascript %}

{% block local_jsx %}
	{{ block.super }}
	<script type="text/babel" src="{% static 'player_acct/js/dashboard_team_panel.jsx' %}"></script>
{% endblock local_jsx %}

{% block banner %}
    <div class="row full-width no-padding dashboard-team-panel index-info-container">
    	<div class="small-0 medium-5 columns"></div>
    	<div class="small-12 medium-2 columns"><h2 class="dashboard-team-header">Teams</h2></div>
    	<div class="small-0 medium-5 columns"></div>
		<div class="small-12 columns content-wrapper" data-local-username="{{ user.player.username }}" id="react-team-view" data-endpoint="{% url 'dota:api-team-player-list' player_id %}" >
		</div>
	</div>
{% endblock banner %}

scrimio/player_acct/templates/player_acct/friends_list.html
{% extends "scrimio/base.html" %}
{% load static %}

{% block local_jsx %}
	{{ block.super }}
	<script type="text/babel" src="{% static 'player_acct/js/friends_list_page.jsx' %}"></script>
{% endblock local_jsx %}

{% block content %}
	<div id="react-friends-list" data-endpoint="{% url 'user:api-player-detail' pk=user.pk %}">
	</div>
{% endblock content %}

scrimio/player_acct/templates/player_acct/user_new.html
{% extends "scrimio/base.html" %}
{% load static %}

{% block local_jsx %}
	{{ block.super }}
		<script type="text/babel" src="{% static 'player_acct/js/user_new_form.jsx' %}"></script>
{% endblock local_jsx %}

{% block local_javascript %}
	{{ block.super }}
	<script src="{% static 'scrimio/js/cookie.js' %}"></script> <!-- JQuery Cookie Manager-->
{% endblock local_javascript %}

{% block content %}
	<div class="row" id="react-player-form" data-endpoint="{% url 'user:api-player-list' %}" data-successRedirect="http://127.0.0.1:8000/user/dashboard/" >
	</div>
{% endblock content%}