scrimio/dota_mm/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.Index, name="index"),
	# Team Generic View
	url(r'^teams/create/$', views.TeamCreate, name="team-create"),
	# Team Specific View
	url(r'^teams/(?P<pk>[0-9]+)/$', views.TeamView, name="team-view"),
	url(r'^teams/(?P<pk>[0-9]+)/edit', views.TeamEditView, name="team-edit"),
	# User Specific View
	url(r'^user/teams/$', views.PlayerTeamView, name="player-team-list"),
	# Match Specific View
	url(r'^match/(?P<pk>[0-9]+)/$', views.GameMatchView, name="match-view"),
	# Match Specific API
	url(r'^api/match/(?P<pk>[0-9]+)/$', views.API_MatchDetail.as_view(), name="match-view"),
	# User Specific API
	url(r'^api/user/(?P<pk>[0-9]+)/$', views.API_GamePlayerDetail.as_view(), name="api-player-detail"),
	url(r'^api/user/(?P<pk>[0-9]+)/teams/$', views.API_GamePlayerTeamList.as_view(), name="api-team-player-list"),
	# Team Generic API
	url(r'^api/teams/$', views.API_TeamCreate.as_view(), name="api-team-list"),
	# Team Specific API
	url(r'^api/team/(?P<pk>[0-9]+)/$', views.API_TeamDetail.as_view(), name="api-team-detail"),
	url(r'^api/team/(?P<pk>[0-9]+)/update/$', views.API_TeamEdit.as_view(), name="api-team-update"),
	url(r'^api/team/(?P<pk>[0-9]+)/destroy/$', views.API_TeamDelete.as_view(), name="api-team-destroy"),
]

scrimio/player_acct/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
	url(r'^dashboard/$', views.player_dashboard, name='user-dashboard'),
	url(r'^friends/$', views.player_friends_list, name='user-friends'),
	url(r'^new/$', views.player_new, name="player-new"),
	url(r'^api/user/$', views.UserList.as_view(), name="api-player-list"),
	url(r'^api/user/(?P<pk>[0-9]+)/$', views.UserDetail.as_view(), name="api-player-detail"),
]

scrimio/scrimio/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from . import views


urlpatterns = [
    url(r'', include('social.apps.django_app.urls', namespace='social')),     # Django Social Auth Login
    url(r'^$', views.index, name='index'),                                    # Index Page
    url(r'^user/', include('player_acct.urls', namespace='user')),            # Scrimio User Information
    url(r'^dota/', include('dota_mm.urls', namespace='dota')),                # Scrimio User Information
    url(r'^admin/', admin.site.urls),                                         # Admin Page
]

scrimio/scrimio/views.py
from django.shortcuts import render

# Scrimio Home Page
def index(request):
	return render(request, 'scrimio/index.html')

scrimio/scrimio/templates/scrimio/base.html
{% load compress %}
{% load static %}
<!DOCTYPE html>
</html>
	<head>
		{% block remote_javascript %}
		<!-- ReactJS Front End -->
		<script src="https://unpkg.com/react@15.3.2/dist/react.js"></script>
	    <script src="https://unpkg.com/react-dom@15.3.2/dist/react-dom.js"></script>
	    <script src="https://unpkg.com/babel-standalone@6.15.0/babel.min.js"></script>
	    <!-- JQuery -->
	    <script src="https://unpkg.com/jquery@2.1.0/dist/jquery.min.js"></script>
	    <!-- Foundation Compressed JavaScript -->
		<script src="https://cdn.jsdelivr.net/foundation/6.2.3/foundation.min.js"></script>
		{% endblock remote_javascript %}

		<!-- Local, Compressed Javascript -->
		{% compress js %}
		{% block local_javascript%}
		{% endblock local_javascript %}
		{% endcompress %}

		<!-- Local JSX -->
		{% block local_jsx %}
		{% endblock local_jsx %}
		
		{% block remote_css %}
		<!-- Foundation Compressed CSS -->
		<link rel="stylesheet" href="https://cdn.jsdelivr.net/foundation/6.2.3/foundation.min.css">
		<!-- Viewport Set -->
		<meta name="viewport" content="width=device-width, initial-scale=1">
		
		<!-- Font Loading -->
		<link href="https://fonts.googleapis.com/css?family=Arimo:400,700" rel="stylesheet">
		{% endblock remote_css %}


		{% compress css %}
		{% block local_css %}
		<!-- Load Base.css Stylesheet-->
		<link rel="stylesheet" type="text/x-scss" href="{% static 'scrimio/css/base.scss' %}">
		{% endblock local_css %}
		{% endcompress %}

		{% block title %}
		<title>Scrimio</title>
		{% endblock title %}
		
	</head>
	<body>
		<!-- In-Page Header -->
		<div class="row top-bar full-width content-wrapper">
			<div class="small-3 columns logo-area">
				<h4 id='logo-text'>SCRIMIO</h4>
			</div>
			<div class="small-9 columns nav-area">
				<a class ="nav-bar-link" href="{% url 'index' %}">Home</a>
				<a class ="nav-bar-link" href="{% url 'user:user-dashboard' %}">Profile</a>
				<a class ="nav-bar-link" href="{% url 'dota:player-team-list' %}">Teams</a>
				<a class ="nav-bar-link" id="nav-bar-link-clear" href="">Tournaments</a>
			</div>
		</div>
		<!-- Page Content -->
		<div class="content">
			<!-- Full Width Content-->
			{% block banner %}
			{% endblock banner %}

			<!-- Standard Content -->
			<div class="row content-wrapper">
				{% block content %}
				{% endblock content %}
			</div>

			{% block full_width_content %}
			{% endblock full_width_content %}
		</div>
		<div class="row bottom-bar full-width content-wrapper">
		</div>
	</body>
</html>

scrimio/scrimio/templates/scrimio/index.html
{% extends "scrimio/base.html" %}
{% load static %}

{% block local_javascript%}
	<script src="{% static 'scrimio/js/fader.js' %}"></script>
{% endblock local_javascript %}


<!-- Full Width Content -->
{% block banner %}
	<div class="row full-width no-padding">
		<div class="small-12 columns video-container full-width no-padding">
			<div class="video-tagline-row row">
				<div class="small-0 medium-2 columns">
				</div>
				<div class="small-12 medium-8 columns">
					<h2 class="video-tagline">Make Your Mark.</h2>
				</div>
				<div class="small-0 medium-2 columns">
				</div>
			</div>
			<img src="{% static 'scrimio/img/front_page_banner.png' %}"/>
		</div>
	</div>
	<div class="row full-width no-padding index-anchor-list-row">
		<div class="small-0 medium-2 columns">
		</div>
		<div class="small-12 medium-8 columns index-anchor-list-container">
			<ul class="inline-list">
				<li>About</li>
				<li>Games</li>
				<li>Matchmaking</li>
				<li>Tools</li>
				<li>Features</li>
			</ul>
		</div>
		<div class="small-0 medium-2 columns">
		</div>
	</div>
	<div class="row full-width no-padding index-info-container">
{% endblock banner %}

<!-- Wrapped Content -->
{% block content %}
		<div class="row">
			<div class="medium-12 columns index-info-section">
				<div class="row full-width no-padding">
					<div class="column small-0 medium-3">
					</div>
					<div class="small-12 medium-6 columns index-info-what-is-scrimio">
						<img class="index-small-header-icon" src="{% static 'scrimio/img/gamepad_icon.png' %}" />
						<div class="index-what-header-icon-underline"></div>
						<h2 class="centered-text info-text index-info-header">What Is Scrimio?</h2>
						<p class="centered-text info-text">Scrimio is an all-in-one esports scrim finder and team management tool designed to give players and managers alike time to focus on what matters: building your team.
						</p>
					</div>
					<div class="column small-0 medium-3">
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock content %}

{% block full_width_content %}
		<div class="row full-width no-padding index-support-container">
			<div class="small-0 medium-2 columns">
			</div>
			<div class="small-12 medium-8 columns">
				<img class="index-support-gif-header" src="{% static 'scrimio/gif/game_icon_header.gif' %}"/>
				<h2 class="centered-text index-support-header-text">We Proudly Support</h2>
				<div class="index-support-header-underline">
				</div>
			</div>
			<div class="small-0 medium-2 columns">
			</div>
		</div>
		<div class="row index-support-game-icon-container">
			<!-- Game Button -->
	    	<div class="small-3 columns dashboard-game-button">
	    		<!-- Icon Row -->
	    		<div class="row">
	    			<div class="small-12 column">
	    				<img class="index-support-game-icon" src="{% static 'scrimio/img/game_icon_dota_shdw.png' %}">
	    			</div>
	    		</div>
	    	</div>
	    	<!-- Game Button -->
	    	<div class="small-3 columns dashboard-game-button">
	    		<!-- Icon Row -->
	    		<div class="row">
	    			<div class="small-12 column">
	    				<img class="index-support-game-icon" src="{% static 'scrimio/img/game_icon_lol_shdw.png' %}">
	    			</div>
	    		</div>
	    	</div>
	    	<!-- Game Button -->
	    	<div class="small-3 columns dashboard-game-button">
	    		<!-- Icon Row -->
	    		<div class="row">
	    			<div class="small-12 column">
	    				<img class="index-support-game-icon" src="{% static 'scrimio/img/game_icon_battlerite_shdw.png' %}">
	    			</div>
	    		</div>
	    	</div>

	    	<!-- Game Button -->
	    	<div class="small-3 columns dashboard-game-button">
	    		<!-- Icon Row -->
	    		<div class="row">
	    			<div class="small-12 column">
	    				<img class="index-support-game-icon" src="{% static 'scrimio/img/game_icon_ow_shdw.png' %}">
	    			</div>
	    		</div>
	    	</div>
		</div>
		<div class="row index-signup-container full-width">
			<div class="small-12 columns section-break">
				<div class="row">
					<div class="small-12 columns signup-header">
						<h2 class="fade">Sign Up</h2>
					</div>
				</div>
				<div class="row">
					<div class="small-12 columns index-google-login fade">
						<button class='index-google-login-button'><a href="{% url 'social:begin' 'google-oauth2' %}">Sign In With Google</a></button>
					</div>
				</div>
			</div>
		</div>
{% endblock full_width_content %}