scrimio/dota_mm/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.Index, name="index"),
	# Team Generic View
	url(r'^teams/create/$', views.TeamCreate, name="team-create"),
	# Team Specific View
	url(r'^teams/(?P<pk>[0-9]+)/$', views.TeamView, name="team-view"),
	url(r'^teams/(?P<pk>[0-9]+)/edit', views.TeamEditView, name="team-edit"),
	# User Specific View
	url(r'^user/teams/$', views.PlayerTeamView, name="player-team-list"),
	# Match Specific View
	url(r'^match/(?P<pk>[0-9]+)/$', views.GameMatchView, name="match-view"),
	# Match Specific API
	url(r'^api/match/(?P<pk>[0-9]+)/$', views.API_MatchDetail.as_view(), name="match-view"),
	# User Specific API
	url(r'^api/user/(?P<pk>[0-9]+)/$', views.API_GamePlayerDetail.as_view(), name="api-player-detail"),
	url(r'^api/user/(?P<pk>[0-9]+)/teams/$', views.API_GamePlayerTeamList.as_view(), name="api-team-player-list"),
	# Team Generic API
	url(r'^api/teams/$', views.API_TeamCreate.as_view(), name="api-team-list"),
	# Team Specific API
	url(r'^api/team/(?P<pk>[0-9]+)/$', views.API_TeamDetail.as_view(), name="api-team-detail"),
	url(r'^api/team/(?P<pk>[0-9]+)/update/$', views.API_TeamEdit.as_view(), name="api-team-update"),
	url(r'^api/team/(?P<pk>[0-9]+)/destroy/$', views.API_TeamDelete.as_view(), name="api-team-destroy"),
]

scrimio/scrimio/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from . import views


urlpatterns = [
    url(r'', include('social.apps.django_app.urls', namespace='social')),     # Django Social Auth Login
    url(r'^$', views.index, name='index'),                                    # Index Page
    url(r'^user/', include('player_acct.urls', namespace='user')),            # Scrimio User Information
    url(r'^dota/', include('dota_mm.urls', namespace='dota')),                # Scrimio User Information
    url(r'^admin/', admin.site.urls),                                         # Admin Page
]

scrimio/dota_mm/models.py
from django.db import models
from django.dispatch import receiver
from django.db.models.signals import post_save
from player_acct.models import Player
import datetime
from .app_settings import GAME_NAME, TEAM_SIZE, ELO_MODIFIER
from django.core.exceptions import ValidationError

from .websocket_transactions import ws_send_team_queue_update, ws_send_player_queue_update
from .status import GAMEPLAYER_STATUS_CHOICES, MUTEX_STATUS, OFFLINE, READY, IN_QUEUE

class GamePlayer(models.Model):
	'''
	Player specific to game

	Local Fields:
	----------------
	- user_acct: Link to Scrimio specific user account
	- elo: User's current game skill ranking

	Related Fields:
	----------------
	- current_team: Link to Team user is currently involved with live
	- teams: List of teams user is enrolld on
	- captain_of: List of teams user is in charge of

	'''
	user_acct = models.ForeignKey(Player, related_name=('%s_player' % (GAME_NAME,)))
	elo = models.IntegerField(default=500)

	# Automatically create a game specific player for the new account
	@receiver(post_save, sender=Player)
	def acct_player_post_save(sender, instance, created, *args, **kwargs):
		if created:
			game_player = GamePlayer.objects.create(user_acct=instance)

	def is_busy(self):
		return self.status.is_busy()

	def is_ready(self):
		return self.status.state is READY

	def register_win(self):
		self.elo = self.elo + ELO_MODIFIER
		self.save()

	def register_loss(self):
		self.elo = self.elo - ELO_MODIFIER
		self.save()

class Team(models.Model):
	'''
	Game specific Team
	'''
	__diff_is_queued = None

	name = models.SlugField(max_length=20)
	description = models.TextField(max_length=200)
	players = models.ManyToManyField(GamePlayer, related_name='teams')
	# Team Scrimio Rank
	elo = models.IntegerField(default=500)
	captain = models.ForeignKey(GamePlayer, related_name="captain_of")
	is_queued = models.BooleanField(default=False)
	
	def __unicode__(self):
		return self.name
		
	def clean(self, *args, **kwargs):
		'''
		Check team size
		'''
		#related_objs = self.players

		#if related_objs:
		#	if len(related_objs) > TEAM_SIZE:
		#		raise ValidationError('Maximum team size is %s players.' % TEAM_SIZE)

		super(Team, self).clean(*args, **kwargs)

	def save(self, *args, **kwargs):
		'''
		# Check if queue status has been updated
		if self.is_queued != self.__diff_is_queued:
			# Send queue update realtime notification
			ws_send_team_queue_update(self.name, self.is_queued)
			# Cache new value
			self.__diff_is_queued = self.is_queued
		'''
		# Invoke all validation every save
		self.full_clean()
		super(Team, self).save(*args, **kwargs)

	def is_game_player_on_team(self, player):
		return player in self.players.all() or player.pk == self.captain.pk

class Status(models.Model):

	__diff_state = None

	player = models.OneToOneField(GamePlayer, on_delete=models.CASCADE, related_name="status", primary_key=True)
	state = models.IntegerField(default=OFFLINE, choices=GAMEPLAYER_STATUS_CHOICES)
	current_team = models.ForeignKey(Team, related_name="reserved_players", null=True, blank=True, default=None)

	# Automatically create a game specific player for the new account
	@receiver(post_save, sender=GamePlayer)
	def game_player_post_save(sender, instance, created, *args, **kwargs):
		if created:
			player_status = Status.objects.create(player=instance)

	def is_busy(self):
		return self.state in MUTEX_STATUS

	'''
	def clean(self, *args, **kwargs):
		# Check if state transition is allowed
		if self.__diff_state != None and self.__diff_state != self.state:
			if self.__diff_state in MUTEX_STATUS and self.state in MUTEX_STATUS:
				raise ValidationError("Cannot transition between %s and %s" % (self.__diff_state, self.state,))
			
		super(Match, self).clean(*args, **kwargs)


	def save(self, *args, **kwargs):
		# Invoke all validation every save
		self.full_clean()

		# Check if queue status has been updated
		if self.state != self.__diff_state:
			# IN_QUEUE -> state
			if self.__diff_state == IN_QUEUE:
				ws_send_player_queue_update(self.current_team.name, self.player.username, False)
			# state -> IN_QUEUE
			elif self.state == IN_QUEUE:
				ws_send_player_queue_update(self.current_team.name, self.player.username, True)
			
			self.__diff_is_queued = self.is_queued

		super(Team, self).save(*args, **kwargs)
	'''


class Match(models.Model):
	'''
	Single instance of Game's match
	'''
	match_id = models.AutoField(primary_key=True)
	# Time the match started
	start_timestamp = models.DateTimeField(default=datetime.datetime.now(), blank=True)
	# Time the match ended
	end_timestamp = models.DateTimeField(default=None, blank=True)
	# Winning team
	winner = models.ForeignKey(Team, null=True, blank=True, default=None)
	# Was the match disputed?
	is_disputed = models.BooleanField(default=False)
	teams = models.ManyToManyField(Team, related_name='matches')
	# How much elo changes for players (zero-sum game)		
	elo_modifier = models.IntegerField(default=25)

	# Check if user exists in match
	def is_player_in_match(self, game_player):
		# Is player on a team within this match?
		for team in self.teams.all():
			if team.is_game_player_on_team(game_player):
				return True
		return False

	def clean(self, *args, **kwargs):
	 	# Ensure end time is after start time
		if end_timestamp != None and start_timestamp > end_timestamp:
			raise ValidationError("A match cannot start after it ends!")
		super(Match, self).clean(*args, **kwargs)

	def save(self, *args, **kwargs):
		# Invoke all validation every save
		self.full_clean()
		super(Match, self).save(*args, **kwargs)

scrimio/dota_mm/views.py
from .app_settings import APP_NAME, GAME_NAME
from django.shortcuts import render, redirect
from rest_framework import generics, mixins, status
from .serializers import TeamSerializer, GamePlayerSerializer, GamePlayerTeamSerializer, TeamDataSerializer, MatchSerializer
from rest_framework.response import Response
from django.http import Http404
from django.views.decorators.csrf import requires_csrf_token

from .models import Team, GamePlayer, Match

#------------# Generic Pages #-------------#

def Index(request):
	return render(request, APP_NAME.format('/index.html'))

#--------------# Team Pages #--------------#

@requires_csrf_token # Ensure CSRF token is given despite lack of {% csrf_token %} in template
def TeamCreate(request):
	if request.user.is_authenticated():
		return render(request, build_url('/create_team.html'), {'user': request.user, 'player_id': request.user.pk})
	else:
		return redirect('index')

def TeamView(request, pk):
	if request.user.is_authenticated():
		return render(request, build_url('/view_team.html'), {'team_id' : pk})

@requires_csrf_token # Ensure CSRF token is given despite lack of {% csrf_token %} in template
def TeamEditView(request, pk):
	try:
		team = Team.objects.get(pk=pk)
	except Team.DoesNotExist:
		# Team doesn't exist
		return render(request, 'scrimio/index.html')

	if request.user.is_authenticated() and team.captain.id == request.user.pk:
		return render(request, build_url('/edit_team.html'), {'user':request.user, 'teamPK':pk})

def PlayerTeamView(request):
	if request.user.is_authenticated():
		return render(request, build_url('/view_player_teams.html'), {'player_id':request.user.pk})

def GameMatchView(request, pk):
	try:
		match = Match.objects.get(match_id=pk)
	except Match.DoesNotExist:
		# Match doesn't exist
		return render(request, 'scrimio/index.html')

	return render(request, build_url('/view_match.html'), {'match_id': pk})

#---------------# Team API #---------------#

# Get list of all teams
class API_TeamCreate(generics.CreateAPIView):
	queryset = Team.objects.all()
	serializer_class = TeamSerializer

class API_TeamDelete(generics.GenericAPIView, mixins.DestroyModelMixin):
	queryset = Team.objects.all()
	serializer_class = TeamSerializer

	def delete(self, request, *args, **kwargs):
		try:
			instance = self.get_object()
			if instance.captain.pk == getattr(request.user.player, ("%s_player" % GAME_NAME)).get().pk:
				return self.destroy(request, *args, **kwargs)
			else:
				return Response(status=status.HTTP_401_UNAUTHORIZED)
		except Http404:
			pass

		return Response(status=status.HTTP_204_NO_CONTENT)

class API_TeamEdit(generics.UpdateAPIView):
	queryset = Team.objects.all()
	serializer_class = TeamSerializer

# Get detail of specific team
class API_TeamDetail(generics.RetrieveAPIView):
    queryset = Team.objects.all()
    serializer_class = TeamDataSerializer

# Get data of a specific GamePlayer
class API_GamePlayerTeamList(generics.RetrieveAPIView):
	queryset = GamePlayer.objects.all()
	serializer_class = GamePlayerTeamSerializer

# Get data of a specific GamePlayer
class API_GamePlayerDetail(generics.RetrieveAPIView):
	queryset = GamePlayer.objects.all()
	serializer_class = GamePlayerSerializer

class API_MatchDetail(generics.RetrieveAPIView):
	queryset = Match.objects.all()
	serializer_class = MatchSerializer

#---------# Utility Functions #------------#

# Builds url based on endpoint and app_name using modulo
def build_url(endpoint):
	info = (APP_NAME, endpoint)
	return("%s%s" % info)

scrimio/dota_mm/templates/dota_mm/create_team.html
{% extends "scrimio/base.html" %}
{% load static %}

{% block local_jsx %}
	{{ block.super }}
	<script src="{% static 'scrimio/js/cookie.js' %}"></script> <!-- JQuery Cookie Manager-->
	<script type="text/babel" src="{% static 'dota_mm/js/create_team_form.jsx' %}"></script>
{% endblock local_jsx %}

{% block content %}
	<div class="row">
		<div class="medium-2 columns">
		</div>
		<div class="medium-10 columns">
			<h1>CREATE TEAM</h1>
		</div>
	</div>
	<div class="row">
		<div class="medium-2 columns">
		</div>
		<div class="medium-8 columns">
			<div class="row" id="react-team-form" data-endpoint="{% url 'dota:api-team-list' %}" data-successRedirect="{% url 'index' %}" data-userPK="{{ user.pk }}">
			</div>
		</div>
		<div class="medium-2 columns">
		</div>
	</div>
	
{% endblock content %}

scrimio/dota_mm/templates/dota_mm/edit_team.html
{% extends "scrimio/base.html" %}
{% load static %}

{% block local_jsx%}
	{{ block.super }}
	<script src="{% static 'scrimio/js/cookie.js' %}"></script> <!-- JQuery Cookie Manager-->
	<script type="text/babel" src="{% static 'dota_mm/js/edit_team_form.jsx' %}"></script>
{% endblock local_jsx %}

{% block content %}
	<div class="row">
		<div class="medium-2 columns">
		</div>
		<div class="medium-10 columns">
			<h1>EDIT TEAM</h1>
		</div>
	</div>
	<div class="row">
		<div class="small-0 medium-2 columns">
		</div>
		<div class="small-12 medium-8 columns">
			<div class="row" id="react-team-form" data-get-endpoint="{% url 'dota:api-team-detail' teamPK %}" data-post-endpoint="{% url 'dota:api-team-update' teamPK %}" 
			data-delete-endpoint="{% url 'dota:api-team-destroy' teamPK %}" data-successRedirect="{% url 'dota:team-edit' teamPK %}" data-userPK="{{ user.pk }}" 
			data-deleteRedirect="{% url 'dota:player-team-list' %}" >
			<!-- -->
			</div>
		</div>
		<div class="small-0 medium-2 columns">
		</div>
	</div>
	
{% endblock content %}

scrimio/dota_mm/templates/dota_mm/index.html
{% extends "scrimio/base.html" %}
{% load static %}

{% block content %}
	<div class="small-12 columns no-padding">
		<p>Hello</p>
	</div>
{% endblock content %}

scrimio/dota_mm/templates/dota_mm/view_match.html
{% extends "scrimio/base.html" %}
{% load static %}

{% block local_jsx %}
	{{ block.super }}
	<script type="text/babel" src="{% static 'dota_mm/js/view_match.jsx' %}"></script>
{% endblock local_jsx %}

{% block content %}
	<div class="small-12 columns no-padding">
		<div class="small-12" id="react-match-view" data-endpoint="{% url 'dota:match-view' match_id %}">

		</div>
	</div>
{% endblock content %}

scrimio/dota_mm/templates/dota_mm/view_player_teams.html
{% extends "scrimio/base.html" %}
{% load static %}

{% block local_jsx %}
	{{ block.super }}
	<script type="text/babel" src="{% static 'dota_mm/js/view_player_teams.jsx' %}"></script>
	<script type="text/javascript" src="{% static 'dota_mm/js/ws_team_login.js' %}"></script>
{% endblock local_jsx %}

{% block content %}
	<div class="small-12 columns" id="react-team-view" data-endpoint="{% url 'dota:api-team-player-list' player_id %}" >
	</div>
{% endblock content %}

scrimio/dota_mm/templates/dota_mm/view_team.html
{% extends "scrimio/base.html" %}
{% load static %}

{% block local_jsx %}
	{{ block.super }}
	<script type="text/babel" src="{% static 'dota_mm/js/view_team.jsx' %}"></script>
{% endblock local_jsx %}

{% block content %}
	<div class="small-12 columns" id="react-team-view" data-endpoint="{% url 'dota:api-team-detail' pk=team_id %}" >
	</div>
{% endblock content %}